<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StudentStoreRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
//        return false;
          return True;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            //
            "name"=>"min:2|max:10",
            "email"=>"email|unique:students",
            "grade"=>"required|max:100",
            "course_id"=>'exists:courses,id'
        ];
    }

    public function messages()
    {
//        return parent::messages(); // TODO: Change the autogenerated stub
        return [
            "name.min"=> "Student name must be at least 2 chars",
            "email.unique"=> "Student with this email already exist",
        ];
    }
}
